#!/usr/bin/env bash
# configures a server to listening on port 80 of all server's active IPv4 IPs
#remove the default nginx configuration file
rm /etc/nginx/sites-enabled/default
#configure Nginx to listen to port 80 for all IPv4 IPs 
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default 
#restart nginx
service nginx restart
